### ISSUE TITLE
Curves for CJT not passing through (0.5, 0.5)

### ISSUE THREAD

**Issue by vinamrsachdeva** [vinamrsachdeva/jury-theorems#3]
For some `n` values, the majority-voter curves don't pass through `(0.5, 0.5)` like they do on the plot published on [CJT's Wikipedia page](https://en.wikipedia.org/wiki/Condorcet%27s_jury_theorem).

For example, look at `n = 12` in the three curves below:

![my deterministic](https://github.com/vinamrsachdeva/jury-theorems/assets/34504513/3606fd6f-768c-472e-9c30-07b1e71b629a)

<p align = "center">Figure 1: Monte Carlo </p>

![my monte carlo](https://github.com/vinamrsachdeva/jury-theorems/assets/34504513/9912384e-d614-47ec-8846-4ff6c9ccd35d)

<p align = "center">Figure 2: Deterministic</p>

![image](https://github.com/vinamrsachdeva/jury-theorems/assets/34504513/1c31feac-7b57-42d8-967a-91e1e46a11f9)

<p align = "center"> Figure 3: Wikipedia</p>

For ease, I'm attaching the relevant functions.

- `montecarlo(p, n, m)` and `deterministic(p, n, m)` from [`theorems/condorcet.py`](https://github.com/vinamrsachdeva/jury-theorems/blob/main/theorems/condorcet.py)

```
def montecarlo(p, n, m): # m is 0 for simple majority
    trials = int(1e6)
    r = majority(n, m)
    if r is None:
        return None
    return np.sum(np.sum((np.random.random(size=(trials, n)) < p).astype(int), axis=1) >= r) / trials

def deterministic(p, n, m): # m is 0 for simple majority
    r = majority(n, m)
    if r == None: return None
    P = 0
    while r <= n:
        P += (comb(n, r) * (p**r) * ((1 - p)**(n-r)))
        r += 1
    return P
```

- `majority(n, m=0)` from [`utils.py`](https://github.com/vinamrsachdeva/jury-theorems/blob/main/utils.py) that `montecarlo` and `deterministic` use

```
def majority(n, m=0):
    if m == 0:
        if n % 2:
            r = (n // 2) + 1
        else:
            r = n // 2
    elif m > 50 and m <= 100: r = ceil((m / 100) * n)
    else:
        print("correctness_simulation(p, n, m) where m = 0 for simple-majority but > 50 and <= 100 for super-majority or unanimity")
        r == None
    return r
```
- [`R` code](https://commons.wikimedia.org/wiki/File:Condorcet%E2%80%99s_jury_theorem_graph.svg#Summary) published on Wikipedia:
```
 # cf. e.g. 
 # Odd case: DOI:10.1016/0176-2680(93)90010-R
 # Even case with coinflip ties: DOI:10.1007/BF01718092
 library(tidyverse); options(scipen=999); library(ggthemes); library(extrafont)
 theme_set(theme_minimal()); theme_update(legend.position = "bottom", text=element_text(family="Lato"))
 
 f <- function(n,p) {
   h=floor(n/2)+1
   if(n %% 2) {
     return(sum(choose(n,seq(h,n)) * p^seq(h,n) * (1-p)^(n-seq(h,n))))
   } else {
     return((sum(choose(n,seq(h,n)) * p^seq(h,n) * (1-p)^(n-seq(h,n)))) +
       (choose(n,n/2) * p^(n/2) * (1-p)^(n/2)) * 1/2) 
   }
 }
 df = tibble(p = seq(0,1,0.01)) %>% rowwise() %>% 
   mutate("1" = f(1,p), "3" = f(3,p), "12" = f(12,p), "100" = f(100,p)) %>% 
   pivot_longer(c("1","3","12","100"), names_to="N", values_to="pg")
 
 df %>% ggplot(aes(p, pg, color=N)) + geom_line() +
   labs(title = element_blank(), x = element_blank(), y = element_blank()) + 
   scale_color_colorblind(breaks=c(1,3,12,100))
 
 ggsave("cjt.svg", width=1000, height=1000, units="px")
```

To me, the functions seem identical but I might be missing something.

**Comment by cmdCrusaderr** [comment]
hey , could you brief me more about the issue?

**Comment by vinamrsachdeva** [comment]
Figure 1 and 2 is what my program produces, Figure 3 is from Wikipedia. I'd suggest read the README file and then run the code on your local machine to get what it's doing.

I've solved this issue for the `deterministic` function by adding this after the `while` loop:

```
    if n % 2 == 0:
        P += (1/2) * (comb(n, (n//2)) * (p**(n//2)) * ((1 - p)**(n-(n//2))))
```

I had missed the `1/2` and the end of the even n value condition in the `R` code.

You can try getting the `montecarlo` function right for the even condition. Basically, you need to add the number of times there will be a tie.

**Comment by vinamrsachdeva** [comment]
I had missed the `1/2` at the end of the even n value condition in the `R` code.
